// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Generator")>]
[<assembly: AssemblyProductAttribute("Elmish.XamarinForms")>]
[<assembly: AssemblyDescriptionAttribute("F# bindings for using elmish in WPF")>]
[<assembly: AssemblyVersionAttribute("0.8.12")>]
[<assembly: AssemblyFileVersionAttribute("0.8.12")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Generator"
    let [<Literal>] AssemblyProduct = "Elmish.XamarinForms"
    let [<Literal>] AssemblyDescription = "F# bindings for using elmish in WPF"
    let [<Literal>] AssemblyVersion = "0.8.12"
    let [<Literal>] AssemblyFileVersion = "0.8.12"
