language: csharp

os: osx
osx_image: xcode9.3

dotnet: 2.1.4

env:
  global:
    - ANDROID_SDK_PATH="/usr/local/share/android-sdk"
    - PATH=$ANDROID_SDK_PATH/platform-tools:$PATH

mono: latest

install:
  - nuget restore

script:
  - ./install-xamarin-android-ios.sh
  - ./build.sh NuGet

