language: csharp

os: osx
osx_image: xcode10

dotnet: 2.1.300

env:
  global:
    - ANDROID_SDK_PATH="/usr/local/share/android-sdk"
    - PATH=$ANDROID_SDK_PATH/platform-tools:$PATH

mono: latest

install:
  - nuget restore

script:
  - mkdir -p build_output
  - ./install-xamarin-android-ios.sh
  - ./build.sh Test

