name: full
# Continuous integration is enabled for master
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - docs/*

jobs:
- job: Windows
  displayName: 'Windows (Complete)'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      echo Install fake-cli and GTK#
      dotnet tool install --tool-path . fake-cli 
      choco install gtksharp
    displayName: 'Install Fake and GTK#'

  - script: |  
      echo run build script
      set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\
      ./build.cmd Full
    displayName: 'Build Fabulous'

  - task: CopyFiles@2
    inputs:
      contents: build_output\*.nupkg
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: Windows-FabulousBuildOutputs

- job: macOS
  displayName: 'macOS (Complete)'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
        echo install fake
        export DOTNET_ROOT=$HOME/.dotnet/
        dotnet tool install fake-cli -g
    displayName: 'Install Fake'

  - script: |
        echo run build script
        export DOTNET_ROOT=$HOME/.dotnet/
        export PATH=$PATH:$HOME/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
        ./build.sh Full
    displayName: 'Build Fabulous'

  - task: CopyFiles@1
    inputs:
      contents: ./build_output/*.nupkg
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: macOS-FabulousBuildOutputs

- job: Linux
  displayName: 'Linux (Complete)'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
        echo install fake
        export DOTNET_ROOT=/usr/share/dotnet
        dotnet tool install fake-cli -g
    displayName: 'Install Fake'

  - script: |
        sudo apt-get update
        sudo apt-get install fsharp
    displayName: 'Install F#'

  - script: |
        echo run build script
        export DOTNET_ROOT=/usr/share/dotnet
        export PATH=$PATH:$HOME/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
        ./build.sh Full
    displayName: 'Build Fabulous'

  - task: CopyFiles@1
    inputs:
      contents: ./build_output/*.nupkg
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: linux-FabulousBuildOutputs
