<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Android" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Browser" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Controls.ColorPicker" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Controls.ItemsRepeater" Version="11.1.5" />
    <PackageVersion Include="Avalonia.Controls.TreeDataGrid" Version="11.1.1" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Headless" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Headless.XUnit" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.iOS" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Labs.Controls" Version="$(AvaloniaLabsVersion)" />
    <PackageVersion Include="Avalonia.Labs.Lottie" Version="$(AvaloniaLabsVersion)" />
    <PackageVersion Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageVersion Include="coverlet.collector" Version="3.1.2" />
    <PackageVersion Include="FsCheck.NUnit" Version="2.16.6" />
    <PackageVersion Include="FSharp.Maui.WinUICompat" Version="1.1.0" />
    <PackageVersion Include="FSharp.Core" Version="9.0.101" />
    <PackageVersion Include="FsUnit" Version="5.6.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="8.0.14" />
    <PackageVersion Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.14" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="NUnit" Version="3.14.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageVersion Include="System.Memory" Version="4.5.5" />
    <PackageVersion Include="xunit" Version="2.9.2" />
  </ItemGroup>
</Project>