// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fabulous.Core")>]
[<assembly: AssemblyProductAttribute("Fabulous.Core")>]
[<assembly: AssemblyDescriptionAttribute("F# Functional App Dev Framework")>]
[<assembly: AssemblyVersionAttribute("0.22.0")>]
[<assembly: AssemblyFileVersionAttribute("0.22.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fabulous.Core"
    let [<Literal>] AssemblyProduct = "Fabulous.Core"
    let [<Literal>] AssemblyDescription = "F# Functional App Dev Framework"
    let [<Literal>] AssemblyVersion = "0.22.0"
    let [<Literal>] AssemblyFileVersion = "0.22.0"
