// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Elmish.XamarinForms.SkiaSharp")>]
[<assembly: AssemblyProductAttribute("Elmish.XamarinForms.SkiaSharp")>]
[<assembly: AssemblyDescriptionAttribute("Elmish.XamarinForms extension for SkiaSharp")>]
[<assembly: AssemblyVersionAttribute("0.12.10")>]
[<assembly: AssemblyFileVersionAttribute("0.12.10")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Elmish.XamarinForms.SkiaSharp"
    let [<Literal>] AssemblyProduct = "Elmish.XamarinForms.SkiaSharp"
    let [<Literal>] AssemblyDescription = "Elmish.XamarinForms extension for SkiaSharp"
    let [<Literal>] AssemblyVersion = "0.12.10"
    let [<Literal>] AssemblyFileVersion = "0.12.10"
