// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fabulous.LiveUpdate")>]
[<assembly: AssemblyProductAttribute("Fabulous.LiveUpdate")>]
[<assembly: AssemblyDescriptionAttribute("F# Functional App Dev Framework Live Update")>]
[<assembly: AssemblyVersionAttribute("0.21.1")>]
[<assembly: AssemblyFileVersionAttribute("0.21.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fabulous.LiveUpdate"
    let [<Literal>] AssemblyProduct = "Fabulous.LiveUpdate"
    let [<Literal>] AssemblyDescription = "F# Functional App Dev Framework Live Update"
    let [<Literal>] AssemblyVersion = "0.21.1"
    let [<Literal>] AssemblyFileVersion = "0.21.1"
