// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fabulous")>]
[<assembly: AssemblyProductAttribute("Fabulous")>]
[<assembly: AssemblyDescriptionAttribute("F# Functional App Dev Framework")>]
[<assembly: AssemblyVersionAttribute("0.17.0")>]
[<assembly: AssemblyFileVersionAttribute("0.17.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fabulous"
    let [<Literal>] AssemblyProduct = "Fabulous"
    let [<Literal>] AssemblyDescription = "F# Functional App Dev Framework"
    let [<Literal>] AssemblyVersion = "0.17.0"
    let [<Literal>] AssemblyFileVersion = "0.17.0"
