#!/usr/bin/env python3
"""Generate a compact inventory of Fabulous backend builders and modifiers."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docs/api/source-inventory.md"
BACKENDS = {
    ".NET MAUI": ROOT / "src/maui/Fabulous.MauiControls",
    "Avalonia": ROOT / "src/avalonia/Fabulous.Avalonia",
}
MEMBER_RE = re.compile(r"^\s*static member(?: inline)?\s+([A-Za-z][A-Za-z0-9_']*)", re.MULTILINE)


def source_members(source_root: Path) -> list[tuple[Path, list[str], list[str]]]:
    entries = []
    for path in sorted(source_root.rglob("*.fs")):
        names = sorted(set(MEMBER_RE.findall(path.read_text(encoding="utf-8"))))
        builders = [name for name in names if name[0].isupper()]
        modifiers = [name for name in names if name[0].islower()]
        if builders or modifiers:
            entries.append((path, builders, modifiers))
    return entries


def generate() -> str:
    lines = [
        "# Source API inventory",
        "",
        "This file is generated by `eng/monorepo/generate-api-reference.py` from public static members in the maintained backend sources. Overloads are listed once; consult the linked source for signatures and XML documentation.",
        "",
    ]

    for backend, source_root in BACKENDS.items():
        entries = source_members(source_root)
        builder_count = len({name for _, builders, _ in entries for name in builders})
        modifier_count = len({name for _, _, modifiers in entries for name in modifiers})
        lines.extend([f"## {backend}", "", f"{builder_count} builder names and {modifier_count} modifier names.", "", "| Source | Builders | Modifiers |", "| --- | --- | --- |"])

        for path, builders, modifiers in entries:
            relative = path.relative_to(ROOT).as_posix()
            link = f"https://github.com/fabulous-dev/Fabulous/blob/main/{relative}"
            lines.append(f"| [{path.name}]({link}) | {', '.join(f'`{name}`' for name in builders) or '-'} | {', '.join(f'`{name}`' for name in modifiers) or '-'} |")

        lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()

    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run {Path(__file__).relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"API reference is current: {OUTPUT.relative_to(ROOT)}")
        return 0

    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())