// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Elmish.XamarinForms")>]
[<assembly: AssemblyProductAttribute("Elmish.XamarinForms")>]
[<assembly: AssemblyDescriptionAttribute("F# bindings for using elmish in WPF")>]
[<assembly: AssemblyVersionAttribute("0.4.5")>]
[<assembly: AssemblyFileVersionAttribute("0.4.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Elmish.XamarinForms"
    let [<Literal>] AssemblyProduct = "Elmish.XamarinForms"
    let [<Literal>] AssemblyDescription = "F# bindings for using elmish in WPF"
    let [<Literal>] AssemblyVersion = "0.4.5"
    let [<Literal>] AssemblyFileVersion = "0.4.5"
