// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Elmish.XamarinForms")>]
[<assembly: AssemblyProductAttribute("Elmish.XamarinForms")>]
[<assembly: AssemblyDescriptionAttribute("F# Functional App Dev Framework")>]
[<assembly: AssemblyVersionAttribute("0.13.8")>]
[<assembly: AssemblyFileVersionAttribute("0.13.8")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Elmish.XamarinForms"
    let [<Literal>] AssemblyProduct = "Elmish.XamarinForms"
    let [<Literal>] AssemblyDescription = "F# Functional App Dev Framework"
    let [<Literal>] AssemblyVersion = "0.13.8"
    let [<Literal>] AssemblyFileVersion = "0.13.8"
