<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UseMaui>true</UseMaui>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <!-- NuGet Package -->
  <PropertyGroup>
    <Description>MediaElement implementation for Fabulous</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>
  <!-- SourceLink -->
  <PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>
  <PropertyGroup Condition="$(GITHUB_ACTIONS) == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\..\logo\nuget-icon.png" Pack="true" PackagePath="\" />
    <Compile Include="Attributes.fs" />
    <Compile Include="MediaElement.fs" />
    <Compile Include="AppHostBuilderExtensions.fs" />
  </ItemGroup>
  <ItemGroup>
    <!--
      FSharp.Core is fixed to a specific version that is not necessarily the latest one.
      This version will be used as the lower bound in the NuGet package
    -->
    <PackageReference Include="CommunityToolkit.Maui" />
    <PackageReference Include="CommunityToolkit.Maui.MediaElement" />

    <PackageReference Include="FSharp.Core" VersionOverride="8.0.300" PrivateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Fabulous.MauiControls\Fabulous.MauiControls.fsproj" />
  </ItemGroup>
</Project>
