// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Elmish.XamarinForms.LiveUpdate")>]
[<assembly: AssemblyProductAttribute("Elmish.XamarinForms.LiveUpdate")>]
[<assembly: AssemblyDescriptionAttribute("F# Functional App Dev Framework Live Update")>]
[<assembly: AssemblyVersionAttribute("0.12.10")>]
[<assembly: AssemblyFileVersionAttribute("0.12.10")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Elmish.XamarinForms.LiveUpdate"
    let [<Literal>] AssemblyProduct = "Elmish.XamarinForms.LiveUpdate"
    let [<Literal>] AssemblyDescription = "F# Functional App Dev Framework Live Update"
    let [<Literal>] AssemblyVersion = "0.12.10"
    let [<Literal>] AssemblyFileVersion = "0.12.10"
