// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Elmish.XamarinForms.Maps")>]
[<assembly: AssemblyProductAttribute("Elmish.XamarinForms.Maps")>]
[<assembly: AssemblyDescriptionAttribute("Elmish.XamarinForms extension for Xamarin.Forms.Maps")>]
[<assembly: AssemblyVersionAttribute("0.12.2")>]
[<assembly: AssemblyFileVersionAttribute("0.12.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Elmish.XamarinForms.Maps"
    let [<Literal>] AssemblyProduct = "Elmish.XamarinForms.Maps"
    let [<Literal>] AssemblyDescription = "Elmish.XamarinForms extension for Xamarin.Forms.Maps"
    let [<Literal>] AssemblyVersion = "0.12.2"
    let [<Literal>] AssemblyFileVersion = "0.12.2"
