// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fabulous.Maps")>]
[<assembly: AssemblyProductAttribute("Fabulous.Maps")>]
[<assembly: AssemblyDescriptionAttribute("Fabulous extension for Xamarin.Forms.Maps")>]
[<assembly: AssemblyVersionAttribute("0.17.0")>]
[<assembly: AssemblyFileVersionAttribute("0.17.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fabulous.Maps"
    let [<Literal>] AssemblyProduct = "Fabulous.Maps"
    let [<Literal>] AssemblyDescription = "Fabulous extension for Xamarin.Forms.Maps"
    let [<Literal>] AssemblyVersion = "0.17.0"
    let [<Literal>] AssemblyFileVersion = "0.17.0"
