// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("fscd")>]
[<assembly: AssemblyProductAttribute("fscd")>]
[<assembly: AssemblyDescriptionAttribute("F# Compiler Daemon")>]
[<assembly: AssemblyVersionAttribute("0.21.1")>]
[<assembly: AssemblyFileVersionAttribute("0.21.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "fscd"
    let [<Literal>] AssemblyProduct = "fscd"
    let [<Literal>] AssemblyDescription = "F# Compiler Daemon"
    let [<Literal>] AssemblyVersion = "0.21.1"
    let [<Literal>] AssemblyFileVersion = "0.21.1"
