site_name: Fabulous Documentation
site_description: Build cross-platform applications in F# with Fabulous.
site_url: https://fabulous-dev.github.io/Fabulous/docs/
repo_url: https://github.com/fabulous-dev/Fabulous
edit_uri: edit/main/docs/

docs_dir: .
theme:
  name: readthedocs

nav:
  - Welcome: README.md
  - Get started: get-started.md
  - Glossary: glossary.md
  - API reference: api/
  - Platforms:
      - .NET MAUI: maui/get-started.md
      - Avalonia: avalonia/get-started.md
  - Core concepts:
      - Overview: basics/README.md
      - Model-View-Update: basics/mvu.md
      - Application state: basics/application-state/README.md
      - Commands: basics/application-state/commands.md
      - State validation: basics/application-state/state-validation.md
  - Advanced:
      - Overview: advanced/README.md
      - Saving and restoring state: advanced/saving-and-restoring-app-state.md
      - Composing larger applications: advanced/composing-larger-applications/README.md
      - Independent MVU states: advanced/composing-larger-applications/splitting-into-independent-mvu-states.md
      - Integrating commands: advanced/composing-larger-applications/integrating-commands.md
      - Communicating between states: advanced/composing-larger-applications/communicating-between-mvu-states.md

exclude_docs: |
  SUMMARY.md
  api/**
  architecture/**
  basics/error-monitoring.md
  basics/testing.md
  basics/user-interface/**
  samples-and-tutorials/**
  advanced/performance-optimization.md

markdown_extensions:
  - admonition
  - fenced_code
  - tables