name: Pull Request
on: pull_request

env:
  SLN_FILE: Fabulous.sln
  CONFIG: Release

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x
    - name: Check code formatting
      run: |
        dotnet tool restore
        dotnet fantomas --check src
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build ${SLN_FILE} -c ${CONFIG} --no-restore
    - name: Test
      run: dotnet test ${SLN_FILE} -c ${CONFIG} --no-build